name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 환경별 properties 파일 생성 - API-KEY
      - name: make application-API-KEY.properties
        run: |
          cd ./src/main/resources
          touch ./application-API-KEY.properties
          echo "${{ secrets.YML_CI }}" > ./application-API-KEY.properties
        shell: bash


      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      - name: Test with JaCoCo
        run: ./gradlew build jacocoTestReport

      - name: Upload JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html/



